### ISSUE TITLE
smbwinexe error

### ISSUE THREAD

**Issue by Saturndrew** [brav0hax/smbexec#3]
Hey Brav0hax, I was trying to install smbexec on my kali linux box and i got this error after selecting option number 4. I am pretty new to linux in general but i was wondering if you could tell me what to do in this case. 

[*] Compiling smbwinexe, this may take a while...
./autogen.sh: need autoconf 2.53 or later to build samba from git
mv: cannot stat `/tmp/smbexec-inst/winexe/source4/bin/winexe': No such file or directory
[!] smbwinexe didn't install properly. Make sure you have prereqs installed...

**Comment by Maleus** [comment]
I was getting this error as well. Running this:  apt-get install \
        gcc-mingw-w64 \
        comerr-dev \
        libpopt-dev \
        libbsd-dev \            
        zlib1g-dev \
        libc6-dev \
        python-dev 

Fixed the issue for me.

**Comment by Saturndrew** [comment]
Thanks! I will try this out (not at work right now) and i will let you know
how it goes.

**Comment by brav0hax** [comment]
The quickest way on Kali is just to cd  into the progs folder and create
symbolic links for smbclient and winexe. They already exist on the distro :)

**Comment by binarymist** [comment]
Nope. Doesn't work. Another clue please?

**Comment by brav0hax** [comment]
If the symbolic link doesn't work then you;re doing it wrong

ln -s /path/to/file /path/to/symlink


On Kali:
cd into /opt/smbexec/progs
ln -s /usr/bin/pth-winexe smbwinexe
ln -s /usr/bin/pth-smbclient smbexeclient

No need to compile any exe's

Everything should work as expected

**Comment by binarymist** [comment]
The symbolic links work fine.
They both (/opt/smbexec/progs/smbclient -> /usr/bin/smbclient & /opt/smbexec/progs/winexe -> /usr/bin/winexe) run the targets fine.

Choice "4.  Compile smbexec binaries" of /opt/smbexec/install.sh appears to fail with:
This script will compile your smbexec binaries
Press any key to continue

[+] Looks like smbexeclient is already compiled, moving to smbwinexe compilation...

[*] Extracting winexe...

[*] Patching winexe to accept hashes...

[*] Compiling smbwinexe, this may take a while
./autogen.sh: need autoconf 2.53 or later to build samba from git mv: cannot stat `/tmp/smbexec-inst/winexe/source4/bin/winexe': No such file or directory
[!] smbwinexe didn't install properly. Make sure you have prereqs installed...

**Comment by brav0hax** [comment]
What I said was you don't need to compile the binaries if you create the
symbolic links....so don't do it.

Skip option 4 if you symbolic links work.

**Comment by binarymist** [comment]
As I said the symbolic links worked fine... The problem was that I didn't link to the correct file (the pth- (passing the hash) derivative). I actually missed that part of your answer as it was folded up, but I spotted it in your email.

So all I had to link to was the following:
ln -s /usr/bin/pth-winexe smbwinexe

The smbexeclient already existed in /opt/smbexec/progs/

Would it be worth adding this to the setup instructions?
Thanks for your help!

**Comment by brav0hax** [comment]
the compilation error is not an error I can fix since its samba. I know
that some people have issues and some dont. Did you ensure you had autoconf
installed? That was the issue it was complaining about

dpkg -s auto-conf

should say "installed ok", then check the version...

I haven't had time to convert to the latest version of samba, but the
workaround I gave you should be just fine.

Thanks,
Eric

**Comment by binarymist** [comment]
So I need auto-conf for the compilation? No I didn't as I wasn't aware it was a pre-req. So you mentioned "Skip option 4 if you symbolic links work" (which they do) smbexec.sh runs which I'm guessing means I don't need auto-conf?

**Comment by brav0hax** [comment]
use pth and just change the yml file to the proper path for each binary.
